name: Perf testing

on:
  push:
    branches:
      - main

jobs:
  perf:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: | 
          pwd
          ls -al

          npm i -g @redocly/cli                && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.122 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.121 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.120 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.119 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.118 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.117 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.116 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.115 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.114 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.113 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.112 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.111 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.110 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.109 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.108 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.107 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.106 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.105 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.104 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.103 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.102 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.101 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
          npm i -g @redocly/cli@1.0.0-beta.100 && redocly --version && time redocly lint openapi/openapi.yaml --format summary || echo $?
